<?php
	/* DWASYS */
	DEFINE ('HOST_DWASYS','192.168.0.6');
	DEFINE ('USER_DWASYS','sa');
	DEFINE ('PASS_DWASYS','myideaS');
	DEFINE ('DB_DWASYS','DWASYS');
	
	/* DWAFINACCT */
	DEFINE ('HOST_DWAFINACCT','192.168.0.6');
	DEFINE ('USER_DWAFINACCT','sa');
	DEFINE ('PASS_DWAFINACCT','myideaS');
	DEFINE ('DB_DWAFINACCT','DWAFINACCT');
?>